### ISSUE TITLE
Unable to access docker Image

### ISSUE THREAD

**Issue by ya-jo-ko** [kai-tub/rico-hdl#6]
Hello, 
I was unable to pull the docker image provided. 
Console output:
Error response from daemon: failed to resolve reference "ghcr.io/kai-tub/rico-hdl:latest": unexpected status from HEAD request to https://ghcr.io/v2/kai-tub/rico-hdl/manifests/latest: 
403 Forbidden

Could you please provide an accessible docker image?

Thank you in advance!

**Comment by kai-tub** [comment]
Hey :wave: 

Thank you for raising this issue!
There was a configuration issue for visibility for the docker package. When I moved the repository from private to public GitHub didn't change the Docker packages from private to public as well (even if everybody can see it).

Either way, it should be fixed now :+1:
